apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    pod : result-app-pod
    app : demo-voting-app # совпадает с другими подами всего контура
spec:
  containers:
    - name : result-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80