apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name : voting-service
    app : demo-voting-app # совпадает с другими подами всего контура
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    pod : voting-app-pod
    app : demo-voting-app # совпадает с другими подами всего контура