apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    owner: RomanFirsov
spec:
  type: LoadBalancer
  selector:
    project: my-web    # Выбор PODS с этими метками
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # порт на Load Balancer
      targetPort: 80  # порт на POD